### ISSUE TITLE
Tensei Shitara Slime Datta Ken 3rd Season problem

### ISSUE THREAD

**Issue by AerosAtar** [erengy/anime-relations#166]
The second half of the third season (eps 13+) from SubsPlease are being recognised as _season 2, part 2_ instead. I imagine this is due to the order of the rules in the file, as I noticed there was an extra S2P2 rule after the S3 rule, but I have no idea if this is actually the case.

**Comment by ghostosenpai** [comment]
>  as I noticed there was an extra S2P2 rule after the S3 rule

you are right about this but it still worked perfectly fine for me

![Screenshot 2024-07-08 135304](https://github.com/erengy/anime-relations/assets/77113812/9a3353e4-b87f-443a-9a97-874437098946)

**Comment by AerosAtar** [comment]
Is it possible that needing to enter an Alternative Title in Taiga in order to get the torrent search to work correctly could be messing with it somehow? Though I have no idea how it would, considering the file is based on id numbers.

![image](https://github.com/erengy/anime-relations/assets/13503100/86da70b3-522e-4df2-89f6-5b42d1fdb8e5)
![image](https://github.com/erengy/anime-relations/assets/13503100/153d2f03-1cc4-41e6-aa4f-891d34a13c44)

**Comment by erengy** [comment]
`Tensei Shitara Slime Datta Ken - 61` is normally identified as S1, which is then redirected to S3. When you manually add `Tensei Shitara Slime Datta Ken` as an alternative title to another series, it takes priority in the recognition process and can affect redirections too.

I think you have a situation where redirection happens twice (S1E61 to S3E13 to S2P2E1) because you added the same alternative title to multiple series. In that case, removing it from any series other than S3 (e.g. S2 and S2P2) should work. Taiga v2 will have a separate option for torrent search, which should also help with similar issues.

**Comment by AerosAtar** [comment]
That seems to be the issue. Removing the alt.title I had on S2P2 has it being recognised correctly as S3. Guess I'll need to try and remember to remove my alt.titles after each season while waiting for Taiga V2. :)
