### ISSUE TITLE
Support for AniDB

### ISSUE THREAD

**Issue by tysdt** [erengy/anime-relations#45]
Hello,

I think that we might want to consider adding a few relations for AniDB to encourages developers to work on AniDB sync support.

**Comment by erengy** [comment]
Hi. Please see #35 for a similar request. Besides, having relations data would have minimal effect on the decision to support a new service (see erengy/taiga#188).

**Comment by purposelycryptic** [comment]
I was going to ask the same thing, not really based on whether Taiga will or will not eventually support AniDB (or any other service), but because the current amount of mapping data is still at a level where it could be added relatively easily to existing entries, and it would take very little additional effort to include it as part of new entries (Every AniDB entry already has a link to the corresponding MAL entry on its page).

It would potentially expand the usefulness of the anime-relations project far beyond just Taiga, thereby also drawing additional contributors (people like me, for example), for whom the current mapping data is not in itself relevant, but for whom the addition of AniDB mappings would immediately make it incredibly attractive.

It would also open the door to very easily adding mapping data for TheTVDB, TMDb and IMDB in the future, since AniDB entries are continually being mapped to those services in [ScudLee's anime-lists](https://github.com/ScudLee/anime-lists). That project uses XML tables to store its mapping data in a way that can be easily converted to Excel spreadsheets, but shouldn't be hard to convert. It may not be of particular interest now, but it is always good to keep your options open.

Anyway, that is just my two cents - I can't do too much myself these days to contribute to much of anything, as I seem to keep getting sicker rather than recovering (Which is also why I haven't really had a chance to even touch the Ryuuji Taiga/Plex-middleware project since creating the repo - really makes me feel like a git :-( ); leaving for another biopsy in a few, to find out whether it's just a really nasty pulmonary disease, or actual cancer. Just hasn't really been my year...
